### PR TITLE
added several new tags and extensions methods

### PR DESCRIPTION
**Pull request by sapiens**
tags added: Label, Textarea, RadioButton

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@sapiens Hey, can you add some tests for the new tags? 

Thanks,

Jeremy

**Comment by sapiens** [comment]
Huh... The Tests project has so many broken deps I've unloaded it (no automatic nuget restore either). I don't want to sound arrogant, but these additions come from my MvcPowerTools library and they are 'battle' tested i.e they work. But if you _really_ want tests, I'll try but I don't know when I'll have some time.

**Comment by jeremydmiller** [comment]
Meh, because the fubu-project.org feed is broken? I haven't touched this codebase in years, so it's no surprise. I'll deal w/ the build tomorrow.

And yeah, even though I'm sure the code is fine and it's simple, I want the tests. If nothing else, it pins down the functionality and gives us examples of how to use the new tags.

**Comment by jbogard** [comment]
@sapiens Do you want to give the tests another try? I've completely removed any Fubu references. It's all VS 2015/project.json files now.

**Comment by sapiens** [comment]
OK, I need some time to understand all the dnx stuff first

**Comment by jbogard** [comment]
I don't think you need to know too much about DNX, the build pulls down anything you need. It should just be code you worry about now (allegedly).

**Comment by sapiens** [comment]
So, I've merged some changes but it seems that Mvc 6 rc2 isn't compatible with dnxcore5. rc1 is. Also for whatever reason I get the message "The type 'HtmlEncoder' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Text.Encodings.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". But the assembly is referenced. Any idea?

**Comment by sapiens** [comment]
Ok, I've downgraded the version for 'System.Text.Encodings.Web' to beta and it works now

**Comment by sapiens** [comment]
Now I have another problem. At every clean/build/ run tests  (from VS) I get this 
```
System.InvalidOperationException: System.MissingMethodException: Method not found: 'Microsoft.Extensions.Logging.ILogger Microsoft.Extensions.Logging.LoggerFactoryExtensions.CreateLogger(Microsoft.Extensions.Logging.ILoggerFactory)'.
```
I think I'm done with this for some time. I think I'm going to wait until MS officially releases coreclr & co

**Comment by jbogard** [comment]
Try again? Also "RadionButton"?

**Pull request closed without merging**
